version: '3'
services:
  zookeeper:
    container_name: zookeeper
    image: debezium/zookeeper:1.7
    ports:
     - 2181:2181
     - 2888:2888
     - 3888:3888
  kafka:
    container_name: kafka
    image: debezium/kafka:1.7
    ports:
     - 9092:9092
    links:
     - zookeeper
    environment:
     - BROKER_ID= 1
     - ZOOKEEPER_CONNECT=zookeeper:2181
     - KAFKA_LISTENERS=INTERNAL://:29092,EXTERNAL://:9092
     - KAFKA_ADVERTISED_LISTENERS= INTERNAL://kafka:29092,EXTERNAL://localhost:9092
     - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP= INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
     - KAFKA_INTER_BROKER_LISTENER_NAME= INTERNAL
  connect:
    container_name: connect
    image: debezium/connect-with-oracle-jdbc:1.7
    build:
      context: debezium-with-oracle-jdbc
      args:
        DEBEZIUM_VERSION: 1.7
        JMX_AGENT_VERSION: 0.15.0
    ports:
     - 5005:5005
     - 1976:1976
     - 8083:8083
    links:
     - kafka
     - oracle-db-source
     - postgres

    volumes:
     - ${PROJECT_PATH}/debezium-with-oracle-jdbc/xstreams.jar /kafka/libs
     - ${PROJECT_PATH}/debezium-with-oracle-jdbc/oracle_instantclient/ojdbc8.jar /kafka/libs
    environment:
     - BOOTSTRAP_SERVERS=kafka:29092
     - GROUP_ID=1
     - CONFIG_STORAGE_TOPIC=my_connect_configs
     - OFFSET_STORAGE_TOPIC=my_connect_offsets
     - STATUS_STORAGE_TOPIC=my_connect_statuses
     - LD_LIBRARY_PATH=/instant_client
     - KAFKA_OPTS=-javaagent:/kafka/etc/jmx_prometheus_javaagent.jar=8080:/kafka/etc/config.yml
     - JMXHOST=localhost
     - JMXPORT=1976
  oracle-db-source:
    container_name: oracle-db-source
    image: heartu41/oracle19c
    ports:
      - 1521:1521
      - 5500:5500
    volumes:
      - ${PROJECT_PATH}/ora-init:/docker-entrypoint-initdb.d
    environment:
    - ORACLE_ALLOW_REMOTE=YES
    - INIT_PGA_SIZE=1000
    - INIT_SGA_SIZE=3000
    - ORACLE_PDB=orcl
    - ORACLE_PWD=password
  postgres:
    container_name: postgres
    image: postgres
    ports:
     - 5432:5432
    environment:
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=postgres
     - POSTGRES_DB=inventory
  kafdrop:
    image: obsidiandynamics/kafdrop
    restart: "no"
    environment:
      KAFKA_BROKERCONNECT: "kafka:29092"
      JVM_OPTS: "-Xms16M -Xmx512M -Xss180K -XX:-TieredCompilation -XX:+UseStringDeduplication -noverify"
    ports:
      - 9000:9000
    depends_on:
      - kafka